
# Pathname to source directory.
set(MEDDYSDKMEDDYPROJECT_SOURCE_PATHNAME "Source")

# Pathname to public source directory.
set(MEDDYSDKMEDDYPROJECT_SOURCE_PATHNAME_PUBLIC "${MEDDYSDKMEDDYPROJECT_SOURCE_PATHNAME}/Public")

# Pathname to private source directory.
set(MEDDYSDKMEDDYPROJECT_SOURCE_PATHNAME_PRIVATE "${MEDDYSDKMEDDYPROJECT_SOURCE_PATHNAME}/Private")

# All public source files.
file(GLOB_RECURSE MEDDYSDKMEDDYPROJECT_SOURCE_FILES_PUBLIC LIST_DIRECTORIES false "${MEDDYSDKMEDDYPROJECT_SOURCE_PATHNAME_PUBLIC}/*")

# All private source files.
file(GLOB_RECURSE MEDDYSDKMEDDYPROJECT_SOURCE_FILES_PRIVATE LIST_DIRECTORIES false "${MEDDYSDKMEDDYPROJECT_SOURCE_PATHNAME_PRIVATE}/*")
